[package]
name = "rcli"
version = "0.1.0"
edition = "2021"
authors = ["xo🦀"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
clap = { version = "4.5.13", features = ["derive"] }
csv = "1.3.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
serde_yaml = "0.9.34"
toml = "0.8.19"
zxcvbn = "3.1.0"
